// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD21U8ezx0Wr7Tl7w_WvqNbBlm2hJGaAsU',
    appId: '1:475151417795:web:aee0587a73259111dd7d76',
    messagingSenderId: '475151417795',
    projectId: 'chats-e7d0e',
    authDomain: 'chats-e7d0e.firebaseapp.com',
    storageBucket: 'chats-e7d0e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpwG2DZnO2R1Rye0zBE_QqIQXB0WSAH7s',
    appId: '1:475151417795:android:3fbd43b5e28d6304dd7d76',
    messagingSenderId: '475151417795',
    projectId: 'chats-e7d0e',
    storageBucket: 'chats-e7d0e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC23GmezeDbLKpTF1itt5E-qOhlv10omUU',
    appId: '1:475151417795:ios:efc7a7a6d4e85598dd7d76',
    messagingSenderId: '475151417795',
    projectId: 'chats-e7d0e',
    storageBucket: 'chats-e7d0e.appspot.com',
    iosClientId: '475151417795-iinvvmc5t8f18t75btesa54eaovfc4n0.apps.googleusercontent.com',
    iosBundleId: 'com.example.clitestChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC23GmezeDbLKpTF1itt5E-qOhlv10omUU',
    appId: '1:475151417795:ios:efc7a7a6d4e85598dd7d76',
    messagingSenderId: '475151417795',
    projectId: 'chats-e7d0e',
    storageBucket: 'chats-e7d0e.appspot.com',
    iosClientId: '475151417795-iinvvmc5t8f18t75btesa54eaovfc4n0.apps.googleusercontent.com',
    iosBundleId: 'com.example.clitestChat',
  );
}
